(ns common-beer-data.fermentables.grains-test
  (:require #? (:clj  [clojure.test :refer [deftest is testing]])
            #? (:cljs [cljs.test    :refer-macros [deftest is testing]])
            [com.wallbrew.spoon.spec :as spoon.spec]
            [common-beer-data.fermentables.grains :as grains]
            [common-beer-format.fermentables :as fermentables]))


(deftest validity-test
  (testing "Ensure static grain definitions are valid"
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/acid-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/amber-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/aromatic-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/barley-flaked))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/barley-raw))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/barley-torrefied))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/biscuit-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/black-patent-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/black-barley-stout))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/brown-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/brumalt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/cara-pils-dextrine))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/carafoam))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/dextrine))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caraamber))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-10l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-20l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-30l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-40l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-60l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-80l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-90l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-120l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-140l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramel-crystal-malt-160l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caramunich-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/carared))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/caravienne-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/chocolate-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/chocolate-malt-uk))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/corn-flaked))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/melanoiden-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/mild-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/munich-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/munich-malt-10l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/munich-malt-20l))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/oats-flaked))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/oats-malted))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/maris-otter-pale-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pale-malt-2-row-belgium))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pale-malt-2-row-uk))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pale-malt-2-row-us))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pale-malt-6-row-us))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/peat-smoked-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pilsner-2-row-belgium))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pilsner-2-row-germany))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/pilsner-2-row-uk))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/rice-flaked))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/roasted-barley))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/rye-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/rye-flaked))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/smoked-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/special-b-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/special-roast))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/toasted-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/victory-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/vienna-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/wheat-malt-belgium))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/dark-wheat-malt))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/wheat-malt-germany))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/wheat-flaked))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/wheat-roasted))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/wheat-torrified))
    (is (spoon.spec/test-valid? ::fermentables/fermentable grains/white-wheat-malt)))
  (testing "Ensure grains group is valid"
    (is (every? #(spoon.spec/test-valid? ::fermentables/fermentable %) (vals grains/grains)))
    (is (every? keyword? (keys grains/grains)))))
